name: Deploy Laravel Application

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
#
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
          ssh-key-passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          source: "."
          target: "/path/to/your/server/spalivewire"

      - name: Run Artisan Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          script: |
            cd /path/to/your/server/spalivewire
            php artisan migrate
            php artisan cache:clear
            # Add other artisan commands as needed
