name: FTP Deploy

on:
  push:
    branches:
      - main  # Deploy on push to the main branch

jobs:
  ftp-deploy:
    name: Deploy Laravel Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: ftp.bivekp18.sg-host.com
          username: kailashgroup@bivekp18.sg-host.com
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./  # The local root directory of your Laravel project
          server-dir: /   # This is the root directory of your remote FTP server
          exclude: |
            .git*
            node_modules/
            vendor/
            .env
            storage/
            tests/
            .github/  # Exclude GitHub actions directory itself
          # dry-run: true  # For testing the exclusions (remove this in production)
          # debug: true    # Enable debug to troubleshoot issues
