name: Deploy Laravel Application

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy via FTP to the root directory of your site
      - name: Deploy to server via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0  # Updated version
        with:
          server: "${{ secrets.FTP_HOST }}"  # Correct variable for FTP server
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./"  # Your Laravel app root
          server-dir: "/"  # Deploy to the root of kailashwithlivewire.bivekp18.sg-host.com

      # Run Artisan commands via HTTP
      - name: Run Artisan Commands via HTTP
        run: |
          curl https://kailashwithlivewire.bivekp18.sg-host.com/artisan/migrate
          curl https://kailashwithlivewire.bivekp18.sg-host.com/artisan/cache-clear
