name: Deploy Laravel Application

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
        env:
          SSH_ASKPASS: /tmp/passphrase.sh

      - name: Provide passphrase
        run: |
          echo "#!/bin/bash" > /tmp/passphrase.sh
          echo "echo ${{ secrets.SERVER_SSH_PASSPHRASE }}" >> /tmp/passphrase.sh
          chmod +x /tmp/passphrase.sh

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: 18765 # Specify the port for SSH
          source: "."
          target: "/www/kailashwithlivewire.bivekp18.sg-host.com"

      - name: Run Artisan Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: 18765 # Specify the port for SSH
          script: |
            cd /www/kailashwithlivewire.bivekp18.sg-host.com
            php artisan migrate
            php artisan cache:clear
